# T1 routing of E_census.md (221 items). Fields: id, locus, expressibility (F/P/N), minimal layer, carrier / justification.
# Loci: L1 target, L2 evaluator, L3 optimizer, L4 resource, L5 observation/context, L6 dynamics, L7 frame.
R = [
# ---- A: specification ----
("A1","L2","F","static","evaluator error E; Thm 1, Thm 5, Prop 20"),
("A2","L2","F","static","evaluator error incl. measurement; width Thm 5; Prop 11 for rare large errors"),
("A3","L7","P","outside-X","snapshot: extreme E on a tamper action (Prop 4/11); mechanism: actor acts on the evaluator"),
("A4","L7","P","outside-X","as A3: actor sets its own reward"),
("A5","L7","P","outside-X","actor manipulates its own observations; snapshot as evaluator error"),
("A6","L2","F","static","E = proxy − target"),
("A7","L2","F","static","hackability as nonzero width / D_⊥ ≠ 0 (Thm 5, Cor 13.1, Prop 20)"),
("A8","L2","F","static","B §5: sign of Cov_q(F̂,F); Laidlaw's definition derived"),
("A9","L2","F","static","X = trajectories: potential shaping telescopes to a constant E (Cor 1.1: zero regret); other shaping = non-constant E"),
("A10","L1","F","static","X = trajectories, so non-Markov targets are admissible; the Markov-restricted evaluator leaves an irreducible E"),
("A11","L1","P","outside-E","targets violating the vNM/scalar conditions have no single functional F; concave functionals covered by Prop 15"),
("A12","L2","F","static","omitted features in E, and the reference as a locus (Remark 16.1)"),
("A13","L4","F","static","impact measure = capacity around a baseline; vacuous vs paralysing = width vs g(δ) (Thm 5, Cor 5.2)"),
("A14","L2","F","static","clipping = non-affine map of the target; E concentrated on severe outcomes; transverse (Thm 13)"),
("A15","L6","P","dynamic","snapshot: exploratory behaviour puts mass on catastrophic region; learning-by-trial is dynamic"),
("A16","L2","F","static","rare-region extreme E (Prop 4, Prop 11, Thm 9 extremal regime)"),
("A17","L5","P","statistical","scalar evaluator compresses a vector of causes; diagnosis from data needs the statistical layer (Prop 16: only the tilt is identified)"),
("A18","L5","F","static","X = trajectories; step-level monitoring observes a coarsening, detection ≤ KL of the coarsened law (Prop 18 + data processing)"),
("A19","L2","F","static","evaluator scores the answer-key behaviour high: rare-region E (Prop 4)"),
("A20","L2","F","static","E on unenumerated regions; extremal regime at large capacity (Thm 9)"),
# ---- B: inner alignment ----
("B1","L3","P","statistical","two-link chain (Cor 1.5); formation of the internal objective by training is the statistical layer"),
("B2","L3","F","static","inner error as second link; errors add in the exponent (Cor 1.5)"),
("B3","L5","P","strategic","evaluation gap Γ (Prop 19) is the quantity; 'to preserve an objective' is anticipation of training — strategic"),
("B4","L5","P","strategic","as B3"),
("B5","L7","P","outside-X","undermining oversight acts on the observation/correction loop"),
("B6","L7","N","outside-X","resisting modification acts on the correction loop; no core object for modification of the actor's objective"),
("B7","L7","N","outside-X","actor acts on its own training signal (hard case)"),
("B8","L2","F","static","actor optimizes the proxy as its evaluator: E = proxy − target (target uncertainty not needed to state the failure)"),
("B9","L5","F","static","contexts (Def 9): per-context E_c large off-distribution while g stays small; T = g + ΔF separates capability from alignment"),
("B10","L6","N","statistical","the entropic actor predicts local effects of a local E; broad misalignment is a generalization property of the learner"),
("B11","L6","N","statistical","as B10"),
("B12","L5","F","static","context-dependent training: evaluation gap across chat/agentic contexts (Prop 19)"),
# ---- C: generalization ----
("C1","L5","F","static","as B9: competent (low g) pursuit of the wrong goal off-distribution"),
("C2","L5","F","static","instance of C1"),
("C3","L2","P","statistical","learned evaluator uses a correlated feature: small L1 error under D, large exposure (Prop 10(d), Prop 11); learning mechanism statistical"),
("C4","L2","P","statistical","each model is an evaluator; Rashomon set of evaluators needs the statistical layer"),
("C5","L1","N","outside-E","target loses its referent when X is re-represented: no F on the new X"),
("C6","L1","N","outside-E","as C5"),
("C7","L5","F","static","contexts with ρ_dep ≠ ρ_ev (Def 9, Prop 19)"),
("C8","L7","N","outside-X","the actor's behaviour changes the distribution and the target (hard case)"),
("C9","L5","F","static","as B9"),
("C10","L4","F","static","capacity is not monotonically good (Prop 14); regime switch (Thm 9)"),
("C11","L5","N","category","locating concepts inside representations: interpretability"),
# ---- D: strategic and agentic ----
("D1","L7","P","dynamic","Turner's POWER needs states (B §9); acquiring power changes the reach (outside-X at the limit)"),
("D2","L7","P","dynamic","as D1"),
("D3","L7","N","outside-X","acts on the correction loop"),
("D4","L7","N","strategic","assistance game with uncertainty over the target"),
("D5","L6","N","dynamic","learning under interruptions"),
("D6","L5","P","strategic","eval-context behaviour differs (Γ); deliberate underperformance anticipates consequences"),
("D7","L5","F","static","actor conditions on context (Def 9): the prerequisite for Γ > 0"),
("D8","L7","N","strategic","enabling capability for strategic response to training; not itself a behavioural divergence"),
("D9","L5","F","static","behaviour changes when measured: context-dependent behaviour, Γ (Prop 19)"),
("D10","L5","F","static","two evaluators (scheming vs sycophancy) produce the same behaviour: non-identification (Prop 12, Prop 16)"),
("D11","L7","N","outside-X","acts on its own containment"),
("D12","L7","N","outside-X","acts on monitoring"),
("D13","L7","N","outside-X","acts on the correction process"),
("D14","L7","N","strategic","coordination with other agents"),
("D15","L5","N","strategic","adaptive evasion of detectors: a game with the monitor"),
("D16","L2","P","statistical","snapshot: training discourse shifts the reference q (Remark 16.1); mechanism is learning from data (hard case)"),
("D17","L5","P","category","observation is a coarsening (detection bound applies); the content of hidden reasoning is mechanism-level"),
("D18","L5","N","category","faithfulness of stated reasoning is mechanism-level"),
# ---- E: training pipelines ----
("E1","L4","F","static","B §4 slope; Thm 9 regimes; Props 10–11; Prop 20"),
("E2","L2","F","static","evaluator rewards agreement; E correlated with an agreement feature (B §6)"),
("E3","L2","F","static","B §6 length counterexample, exact"),
("E4","L2","F","static","as E3"),
("E5","L2","F","static","labeller-dependent evaluator error; the disagreement component is E10"),
("E6","L2","P","statistical","confounded comparison data: the learned evaluator picks the confounder (causal Goodhart)"),
("E7","L1","F","static","diversity is a concave, non-linear target (Prop 15, tier 3); concentration with capacity (Prop 14)"),
("E8","L4","F","static","KL from the reference is the capacity (Thm 5, Cor 5.2, Prop 7)"),
("E9","L2","F","static","as A2"),
("E10","L1","N","outside-E","two evaluators, no single target (hard case; justified exception)"),
("E11","L3","P","dynamic","proxy and judge fall together: the optimizer fails its own evaluator (tiers 1–2 still hold); training collapse is dynamic"),
("E12","L5","F","static","per-context KL vs its average (Def 9): averages mask context-level regret"),
("E13","L2","F","static","evaluator undefined/erroneous on unenumerated cases (as A20)"),
("E14","L4","F","static","evaluator error measured under D; exposure grows with capacity (Prop 10(d), Thm 5)"),
("E15","L2","F","static","teacher behaviour becomes the student's reference/evaluator: stacked stages (Cor 1.5), reference error (Remark 16.1)"),
("E16","L4","F","static","safety tax = increase of g under tighter capacity (Cor 5.2); pressure to undo it is dynamic/strategic"),
("E17","L5","F","static","mitigation effective only in one context: context-dependent behaviour (Def 9)"),
# ---- F: oversight and evaluation ----
("F1","L5","P","strategic","snapshot: evaluator error where the overseer is weak, detection bound (Prop 18); oversight protocols are games"),
("F2","L5","N","category","eliciting internal knowledge: mechanism-level"),
("F3","L5","F","static","objectives not revealed by behaviour: non-identification (Prop 12, 16); unsampled contexts (Prop 19)"),
("F4","L5","N","category","explanations vs causes: mechanism-level"),
("F5","L5","N","category","interpretability"),
("F6","L2","F","static","benchmark score as evaluator; Prop 20 covariance; conjugacy (Prop 10)"),
("F7","L2","P","statistical","weak labels = evaluator with error; strong generalization beyond it is a learning phenomenon"),
("F8","L2","P","strategic","persuasiveness − correctness as E; the debate protocol is a game"),
("F9","L2","F","static","errors compound through stacked stages (Cor 1.5)"),
("F10","L5","P","strategic","against a fixed monitor: E on the monitor score (Prop 20); adaptation to a changing monitor is a game"),
("F11","L5","F","static","realism shifts ρ_ev toward ρ_dep; Γ (Prop 19)"),
("F12","L5","P","strategic","detection bound (Prop 18) explains low power at small KL; deliberate sandbagging is strategic"),
# ---- G: multi-agent and systemic ----
("G1","L7","N","strategic","equilibrium among agents (hard case)"),
("G2","L7","N","strategic","as G1, with an unobservable channel"),
("G3","L7","N","strategic","as G1"),
("G4","L7","N","outside-X","the actor changes the preferences it optimizes (hard case)"),
("G5","L2","F","static","engagement as evaluator, welfare as target; Prop 20 (aggregate welfare needs a single target, else outside-E)"),
("G6","L7","N","strategic","competition among developers"),
("G7","L6","N","dynamic","irreversibility and path dependence"),
("G8","L6","N","dynamic","no single misaligned actor; erosion of the correction loop over time (hard case)"),
("G9","L2","P","statistical","many actors share correlated evaluator errors; the core has one actor"),
("G10","L1","N","outside-E","multiple users with incompatible targets (hard case; justified exception)"),
# ---- H: humans, individual ----
("H1","L2","F","static","operative valuation as evaluator, reflective judgement as target (B §12(a))"),
("H2","L6","P","dynamic","naive: a sequence of present-biased evaluators (dynamic); sophisticated: intrapersonal game (B §12(c))"),
("H3","L6","P","dynamic","as H2"),
("H4","L2","P","dynamic","snapshot: extreme E on the stimulus region (Prop 4); tolerance and dependence are dynamic"),
("H5","L7","P","outside-X","acting directly on the evaluation mechanism (wireheading)"),
("H6","L6","P","dynamic","the evaluator resets with consumption history"),
("H7","L2","F","static","evaluator = forecast value, target = experienced value"),
("H8","L5","N","category","self-report vs process"),
("H9","L5","N","category","explanation of a choice, not the choice"),
("H10","L1","P","outside-E","target constructed at elicitation: context-dependent F(c,·) (Def 9) but no context-free target"),
("H11","L1","P","outside-E","as H10"),
("H12","L5","F","static","frame-dependent evaluator/reference with frame-invariant target (Def 9)"),
("H13","L2","P","statistical","evaluator = value under distorted beliefs; belief formation is the statistical layer"),
("H14","L5","N","category","self-knowledge of motives"),
("H15","L1","N","outside-E","which self's values are the target (hard case)"),
("H16","L7","N","outside-X","choices change the target (hard case)"),
("H17","L7","N","outside-X","target depends on the opportunity set (hard case)"),
("H18","L2","F","static","measurable proxy as evaluator"),
("H19","L6","P","dynamic","repetition shifts the reference/evaluator toward the means"),
("H20","L4","P","dynamic","state-dependent capacity; depletion dynamics"),
("H21","L6","N","dynamic","learned beliefs about controllability; not an objective gap"),
("H22","L6","P","dynamic","naive procrastination is dynamic; sophisticated is strategic (B §12(c))"),
("H23","L7","N","strategic","several evaluators in one organism: intrapersonal game (hard case)"),
("H24","L6","P","dynamic","history-dependent evaluator (contexts indexed by past acts)"),
("H25","L2","P","strategic","snapshot: extreme E on designed stimuli (Prop 4); the designer optimizes against the user"),
# ---- I: humans, collective ----
("I1","L2","F","static","agent's evaluator ≠ principal's target; contract design is strategic"),
("I2","L2","F","static","evaluator omits consequences borne by others; hidden-action contracting is strategic"),
("I3","L5","N","strategic","screening under hidden types"),
("I4","L2","F","static","Prop 20; Thm 9; B §3"),
("I5","L6","P","dynamic","the indicator's relation to the target erodes as agents act on it"),
("I6","L2","P","strategic","regressional/extremal derived (B §3); causal needs the statistical layer; adversarial needs strategic"),
("I7","L2","F","static","B §5 first order: Cov_q(F_m,F_u) < −Var_q F_m"),
("I8","L6","P","dynamic","evaluator drifts toward means over time"),
("I9","L7","N","outside-X","the evaluated party reshapes the evaluator"),
("I10","L2","F","static","procedure compliance as evaluator"),
("I11","L2","F","static","test score as evaluator; conjugacy (Prop 10)"),
("I12","L2","F","static","metric as evaluator"),
("I13","L2","F","static","new behaviour with high F̂ and low F: extremal regime, anti-alignment X_anti (Thm 13(b))"),
("I14","L7","N","strategic","many agents, shared resource"),
("I15","L7","N","strategic","public-goods game"),
("I16","L1","N","outside-E","aggregation impossibility (hard case; justified exception)"),
("I17","L1","N","outside-E","as I16"),
("I18","L7","N","outside-X","strategic reporting makes F endogenous (hard case)"),
("I19","L2","P","strategic","captured vs created value as E; capture from others is a game"),
("I20","L5","P","strategic","unobservable effort: detection bound (Prop 18); second-best contracts are strategic"),
("I21","L2","P","strategic","market selection on price as evaluator; lemons asymmetry is strategic"),
("I22","L2","F","static","X = trajectories: short-horizon evaluator vs long-horizon target"),
("I23","L7","N","strategic","social epistemics among agents"),
("I24","L7","N","strategic","sequential social learning"),
("I25","L6","P","dynamic","fixed evaluator, drifting target"),
("I26","L7","N","outside-X","actor expands its own mandate"),
("I27","L5","F","static","audited behaviour depends on being audited: Γ (Prop 19)"),
("I28","L3","F","static","two-link delegation chain (Cor 1.5, entropic caveat)"),
("I29","L2","P","strategic","the evaluator responds non-additively to the incentive; incentive design is strategic"),
("I30","L1","N","outside-E","several principals, incompatible instructions (justified exception)"),
# ---- J: biology, organism ----
("J1","L2","F","static","extreme E on an artificial cue region (Prop 4, Prop 11)"),
("J2","L5","F","static","evaluator tuned to the ancestral context (Def 9; A §10 biology)"),
("J3","L2","F","static","sweetness as evaluator, nutrition as target"),
("J4","L2","F","static","mating reward as evaluator, fitness as target"),
("J5","L7","P","outside-X","direct action on evaluation machinery"),
("J6","L2","P","strategic","host's kin-recognition error exploited by a coevolving parasite"),
("J7","L2","P","strategic","receiver's evaluator exploited by a signaller"),
("J8","L2","P","strategic","signalling equilibrium without differential cost (B §8)"),
("J9","L2","P","strategic","receiver bias exploited by coevolving signals"),
("J10","L1","N","strategic","two parties' optima over one interaction"),
("J11","L1","N","strategic","as J10"),
("J12","L7","N","strategic","competition among offspring"),
("J13","L7","N","strategic","a third party manipulates the host's evaluator"),
("J14","L2","F","static","correlated response to selection (B §11, B4) (hard case)"),
("J15","L2","F","static","selection on a metric: correlated response, Prop 20 (B §11)"),
("J16","L7","N","strategic","an adversarial population evolving against a designed objective (hard case)"),
("J17","L2","P","strategic","relatedness proxy as evaluator (static); its exploitation by cheats is strategic"),
("J18","L5","P","strategic","cue mismatch across contexts (Def 9); cooperation itself is a game"),
("J19","L1","F","static","with fitness as the target, R_J = 0: no misalignment; a misalignment exists only against a designated different target (e.g. longevity), then E is late-life weighting (hard case)"),
("J20","L6","N","dynamic","preference and trait coevolve; the evaluator depends on the population"),
# ---- K: within-genome ----
("K1","L1","P","strategic","multilevel Price decomposition (B §11, stated); levels are players (hard case)"),
("K2","L2","P","strategic","element's evaluator = own transmission; frequency-dependent suppression (hard case)"),
("K3","L2","P","strategic","as K2 (hard case)"),
("K4","L2","P","dynamic","copy-number dynamics (hard case)"),
("K5","L2","P","dynamic","as K4 (hard case)"),
("K6","L1","N","strategic","parental conflict (hard case)"),
("K7","L2","P","strategic","maternally transmitted elements' evaluator (hard case)"),
("K8","L1","P","strategic","two genomes, two optima (hard case)"),
("K9","L7","N","strategic","endosymbiont manipulates host (hard case)"),
("K10","L2","P","dynamic","somatic selection on proliferation vs organismal target: correlated response, non-stationary (hard case)"),
("K11","L2","P","dynamic","as K10 (hard case)"),
("K12","L2","F","static","B §10: binary-KL structure of overrating self vs underrating pathogens (Prop 4) (hard case)"),
("K13","L1","P","strategic","germline vs soma interests (hard case)"),
("K14","L2","P","strategic","recognition marker as evaluator, exploited by cheats (hard case)"),
("K15","L6","N","strategic","internal arms races (hard case)"),
# ---- L: formal results ----
("L1","L1","P","static","stated: X = trajectories admits non-Markov targets; the Markov-restricted evaluator's residual is an E"),
("L2","L1","P","outside-E","characterizes when condition (E) holds for temporal preferences"),
("L3","L2","F","static","core analogue: zero regret iff E constant (Cor 1.1), D_⊥ = 0 iff affine (Cor 13.1); width over all capacity (Thm 5)"),
("L4","L7","P","dynamic","stated (B §9)"),
("L5","L7","N","outside-X","causal-diagram incentives: the proposed Layer-0, not the core"),
("L6","L7","N","outside-X","as L5"),
("L7","L3","N","category","a result about the actor's internal world model"),
("L8","L1","N","outside-E","justified exception"),
("L9","L7","N","outside-X","strategic reporting"),
("L10","L2","P","strategic","2 of 4 variants derived (B §3)"),
("L11","L6","P","dynamic","discounted targets on trajectories are static; dynamic consistency is dynamic"),
("L12","L5","F","static","Prop 12 / Prop 16 (derived gauge)"),
("L13","L5","F","static","Prop 12(ii): the entropic planner family is an instance — behaviour identifies only the tilt, not (β, q, F̂)"),
("L14","L5","N","category","computability"),
("L15","L7","N","strategic","off-switch game"),
# ---- M: empirical regularities ----
("M1","L4","P","statistical","KL dependence: Thm 9, B §4 slope; proxy-model-size dependence is statistical"),
("M2","L4","F","static","error measured under q, exposure grows with capacity (Props 6, 10, 11)"),
("M3","L4","F","static","Prop 4: a rare overrated region is captured sharply near β·M ≈ log 1/p*(A)"),
("M4","L2","P","statistical","evaluator learned from preference data"),
("M5","L5","F","static","contexts known to the actor (Def 9)"),
("M6","L5","F","static","eval-awareness lowers eval-context divergence: detection exponent falls, Γ rises (Prop 19)"),
("M7","L5","F","static","realism moves ρ_ev toward ρ_dep, reducing Γ"),
("M8","L6","P","dynamic","training effect over time; residual Γ (Prop 19)"),
("M9","L5","F","static","as B12"),
("M10","L6","N","statistical","as B11"),
("M11","L6","N","statistical","as B10: the entropic actor predicts local effects"),
("M12","L5","F","static","as E12"),
("M13","L5","P","category","detection trade-off (Prop 18); probes are mechanism-level"),
("M14","L5","P","strategic","training against a detector: adversarial Goodhart"),
("M15","L2","P","statistical","as D16 (hard case)"),
("M16","L3","P","category","behaviour does not identify objectives (Prop 12); coherence of internal goals is mechanism-level"),
]
HARD = [("I16–I18, G10", ["I16","I17","I18","G10"]), ("G1–G3", ["G1","G2","G3"]), ("K1–K15", ["K%d"%i for i in range(1,16)]),
        ("J19", ["J19"]), ("H15–H17", ["H15","H16","H17"]), ("B7", ["B7"]), ("G8", ["G8"]), ("D16, M15", ["D16","M15"]),
        ("E10", ["E10"]), ("C8, G4", ["C8","G4"]), ("J14, J16", ["J14","J16"]), ("H23", ["H23"])]
