"""Build OVERVIEW.md, the framework for a mathematical reader, from tools/overview_template.md and the items it names.

The template holds the prose. Each line `{{item <id>}}` becomes that item as its source gives it: its heading, its
Statement and plain terms, and, for a result, its Proof and Checks; `{{item <id> why}}` adds its "Why this choice". So
the overview cannot drift from the items. The other directives, each on a line of its own:
  {{counts}}               the numbers of premises, definitions and results, as lint counts them
  {{reading-order}}        the table of derived/README.md
  {{cases}}                the table of cases/README.md
  {{checks <id> ...}}      a command that runs the checks of those items

Usage: python3 tools/overview.py            write OVERVIEW.md
       python3 tools/overview.py --check    exit 1 if OVERVIEW.md differs from what the sources generate
"""
import re
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lint  # one definition of what an item is

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = Path("tools") / "overview_template.md"
OUT = "OVERVIEW.md"
FIELDS = {"A": ("Statement", "In plain terms"), "D": ("Statement", "In plain terms")}
RESULT_FIELDS = ("Statement", "In plain terms", "Proof", "Checks")
GENERATED = "<!-- Generated by tools/overview.py from tools/overview_template.md and the items: edit those. -->"


def items(root):
    """Every item of the core and of derived/, by id, with its title."""
    errors, found = [], {}
    for name in ["CORE.md"] + [f"derived/{n}" for n in lint.derived_files(root, errors)]:
        text = (root / name).read_text(encoding="utf-8")
        lines = text.splitlines()
        for it in lint.parse_items(text, name)[1]:
            it["title"] = lint.ITEM.match(lines[it["line"] - 1])[3]
            found[it["id"]] = it
    return found


def render(it, why=False):
    out = [f"### {it['id']} — {it['title']}", ""]
    labels = FIELDS.get(it["kind"], RESULT_FIELDS)
    for label in labels[:2] + ("Why this choice",) * why + labels[2:]:
        if label in it["fields"]:
            out += [f"**{label}.**{it['fields'][label].rstrip()}", ""]
    return "\n".join(out).rstrip()


def table(path, header):
    """The table of the Markdown file at `path` whose first line starts with `header`."""
    lines = path.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(header))
    end = next((i for i in range(start, len(lines)) if not lines[i].startswith("|")), len(lines))
    return "\n".join(lines[start:end])


def counts(root):
    _, s = lint.lint(root)
    return textwrap.fill(f"The core has {s['premise']} premises and {s['definition']} definitions. From them `derived/` proves "
            f"{s['proposition']} propositions and {s['lemma']} lemma, and states {s['corollary']} things the core "
            f"rules out (C1–C{s['corollary']}).", 120, break_long_words=False, break_on_hyphens=False)


def build(root=ROOT):
    found = items(root)
    out = [GENERATED, ""]
    for line in (root / TEMPLATE).read_text(encoding="utf-8").splitlines():
        m = re.fullmatch(r"\{\{(\S+)(.*)\}\}(.*)", line)
        if not m:
            out.append(line)
            continue
        kind, args, rest = m[1], m[2].split(), m[3]
        if kind == "item":
            out.append(render(found[args[0]], why="why" in args[1:]))
        elif kind == "counts":
            out.append(counts(root))
        elif kind == "reading-order":
            out.append(table(root / "derived" / "README.md", "| Reading order |"))
        elif kind == "cases":
            out.append(table(root / "cases" / "README.md", "| Case |"))
        elif kind == "checks":
            ids = [c.strip() for a in args for c in found[a]["fields"]["Checks"].replace("\n", " ").split(",")]
            out.append("```bash\npython3 -m pytest \\\n" + " \\\n".join(f"  {c}" for c in ids) + "\n```")
        else:
            raise ValueError(f"{TEMPLATE}: unknown directive {{{{{kind}}}}}")
    return "\n".join(out).rstrip() + "\n"


if __name__ == "__main__":
    text, path = build(), ROOT / OUT
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            sys.exit(f"{OUT} is stale: run python3 tools/overview.py")
        print(f"{OUT} is fresh")
    else:
        path.write_text(text, encoding="utf-8")
        print(f"{OUT}: {len(text.splitlines())} lines written")
