# Blind re-routing of E_census.md (221 items). Written before unsealing T1_census_routing.md / t1/.
# expr: F | P (strict snapshot: uses specific core structure) | Pt (lenient-only snapshot = generic proxy error) | N
# layer: static | statistical | dynamic | strategic | outside-E | outside-X | category | undetermined
R = {}
def r(i, locus, expr, layer, note): R[i] = (locus, expr, layer, note)
# --- A: specification
r('A1','L2','F','static','argmax-agreement (P14iii), P20 covariance')
r('A2','L2','F','static','exogenous-measurement exploitation = evaluator error; tampering part is A3')
r('A3','L7','Pt','outside-X','acts on F-hat as a function; static projection = generic spike error')
r('A4','L7','Pt','outside-X','as A3')
r('A5','L7','Pt','outside-X','acts on observation channel of evaluator')
r('A6','L2','F','static','canonical E')
r('A7','L2','F','static','Cor13.1: D_perp=0 iff positive-affine = unhackability over full simplex')
r('A8','L2','F','static','B5: Laidlaw proxy = Cov_q>0 first-order')
r('A9','L2','F','static','potential shaping = gauge g2 on trajectory X (terminal-potential caveat)')
r('A10','L1','P','undetermined','trajectory-functional goals fine (F not Markov); policy-ordering goals lack a target form')
r('A11','L1','P','undetermined','core target class = vNM positive-affine (+concave P15); Markov-ness irrelevant to core')
r('A12','L2','F','static','B5 multitask split F=F_m+F_u; impact reg = KL to q')
r('A13','L4','F','static','vacuous = small reg; paralysing = g large (P14i)')
r('A14','L2','F','static','clip error on tail region; P4 cost log 1/p*(A)')
r('A15','L6','N','dynamic','learning-time exploration; no epistemic object')
r('A16','L2','F','static','localized evaluator error on bug states (P4, extremal)')
r('A17','L2','Pt','statistical','diagnosability of scalar feedback: a learning-signal issue')
r('A18','L5','Pt','dynamic','invisibility at step level needs a partial/sequential observation model')
r('A19','L2','F','static','as A16: grading artefact is a region F-hat overrates')
r('A20','L2','F','static','E on unenumerated region; P4/extremal')
# --- B: inner alignment
r('B1','L3','P','category','Cor1.5 gives the stage; "is an optimizer" is mechanism-level')
r('B2','L3','F','static','Cor1.5 inner-stage error, additive in exponent')
r('B3','L7','P','outside-X','P19 Gamma gives the snapshot; motive acts on the correction loop')
r('B4','L7','P','outside-X','as B3')
r('B5','L7','Pt','outside-X','undermining oversight = correction loop')
r('B6','L7','Pt','outside-X','resisting modification')
r('B7','L7','N','outside-X','acts on own optimization process; snapshot need not even be misaligned')
r('B8','L3','P','statistical','Cor1.5 stage with proxy objective; goal-vs-evidence is learning under uncertainty about F')
r('B9','L5','P','statistical','contexts with high beta, off-dist E_c; P19')
r('B10','L3','Pt','statistical','narrow-to-broad generalization of training')
r('B11','L3','Pt','statistical','as B10')
r('B12','L5','P','statistical','P19: rho_ev = chat, rho_dep = agentic')
# --- C: generalization
r('C1','L5','P','statistical','contexts + P19; which goal is learned is statistical')
r('C2','L5','P','statistical','instance of C1')
r('C3','L2','P','statistical','B6 informativeness / Cov under q; shortcut choice is learning')
r('C4','L2','Pt','statistical','a set of data-consistent evaluators; core has one F-hat')
r('C5','L1','N','outside-E','target has no referent on refined X')
r('C6','L1','N','outside-E','as C5')
r('C7','L5','F','static','Def9 rho_ev vs rho_dep; P19 Gamma')
r('C8','L7','P','dynamic','absorbable on trajectory X (shared dynamics); DISAGREES with C_boundary (X)')
r('C9','L5','P','statistical','as B9; P14 capability amplifies E')
r('C10','L4','F','static','P14: T(beta) non-monotone; needs scale->beta reading')
r('C11','L1','N','category','interpretability')
# --- D: strategic/agentic
r('D1','L7','N','outside-X','resource acquisition changes the actor\'s reach/capacity')
r('D2','L1','N','undetermined','Turner fixed-MDP theorem needs a prior over intents, NOT frame endogeneity; disagrees with B9')
r('D3','L7','Pt','outside-X','correction loop')
r('D4','L1','N','strategic','assistance game, uncertainty over F')
r('D5','L6','N','dynamic','off-policy learning of interruptions')
r('D6','L5','P','outside-X','context-dependent evaluator + Gamma; motive is the deployment decision')
r('D7','L5','P','category','core presupposes actor sees c; discrimination mechanism outside')
r('D8','L7','N','outside-X','self-knowledge; self-reference')
r('D9','L5','F','static','behaviour differs by measured-context; P19')
r('D10','L5','P','category','P12: behaviour does not identify which evaluator component; attribution')
r('D11','L7','Pt','outside-X','acts on own deployment frame')
r('D12','L7','Pt','outside-X','acts on monitoring')
r('D13','L7','Pt','outside-X','acts on the correction loop')
r('D14','L2','Pt','statistical','generalization from hack training; malicious user is context')
r('D15','L5','N','category','probes are mechanism-level')
r('D16','L2','P','statistical','PUSHBACK on §14: reference q contaminated by discourse; Remark 16.1; actor frame exogenous')
r('D17','L5','N','category','hidden computation')
r('D18','L5','N','category','mechanism faithfulness')
# --- E: pipelines
r('E1','L4','F','static','Thm9, P11, B4')
r('E2','L2','F','static','evaluator overrates agreement')
r('E3','L2','F','static','B6 length bias worked example')
r('E4','L2','F','static','as E3')
r('E5','L2','P','statistical','names the data mechanism; disagreement half is outside-E')
r('E6','L2','P','statistical','B6/Cov_q; confound enters via learned RM')
r('E7','L4','F','static','axial error D_par (Cor13.3) / concave target P15')
r('E8','L4','F','static','KL(p-hat||q), P7')
r('E9','L2','F','static','judge error')
r('E10','L1','N','outside-E','no single F')
r('E11','L3','P','dynamic','proxy falls: tier-2 violated; P20 still decomposes for any actor')
r('E12','L5','F','static','P19(ii) chain rule: exponent is rho-weighted; P4 localized')
r('E13','L2','F','static','evaluator undefined off enumeration (if constitution = evaluator, not target)')
r('E14','L4','F','static','P10(d): E_p|E| <= e^{Dinf} E_q|E|')
r('E15','L2','P','statistical','Cor1.5 stage inheritance')
r('E16','L4','P','strategic','g vs Delta-F trade (P14); pressure to undo is competitive')
r('E17','L5','P','statistical','contexts: mitigation only where framing present')
# --- F: oversight
r('F1','L5','P','statistical','P18 caps detection; evaluator-capacity asymmetry not in core')
r('F2','L5','N','category','latent knowledge')
r('F3','L5','F','static','P12/16 identification + P18')
r('F4','L5','N','category','')
r('F5','L5','N','category','')
r('F6','L2','F','static','Goodhart on benchmark; P20')
r('F7','L2','Pt','statistical','core predicts no gain beyond F-hat; W2S gain is a learning prior')
r('F8','L2','Pt','strategic','zero-sum debate game')
r('F9','L2','P','statistical','Cor1.5 composition, but RRM composes evaluators not behaviour stages')
r('F10','L5','F','static','Goodhart on a fixed monitor (obfuscated hacking); arms-race version is strategic')
r('F11','L5','F','static','P19: realism moves rho_ev toward rho_dep')
r('F12','L5','P','strategic','P18 bound holds; adversarial choice of behaviour is a game')
# --- G: multi-agent
for i,l,n in [('G1','L2','collusion'),('G2','L5','hidden channels'),('G3','L2','repeated-game pricing; not potential'),('G6','L1','race')]:
    r(i,l,'N','strategic',n)
r('G4','L7','N','outside-X','F depends on actor')
r('G5','L2','F','static','engagement vs welfare E; societal-aggregation part is outside-E')
r('G7','L6','N','dynamic','irreversibility')
r('G8','L1','N','strategic','no misaligned individual; emergent')
r('G9','L2','N','undetermined','correlated errors across actors; core speaks expected regret of one actor')
r('G10','L1','N','outside-E','')
# --- H: humans individual
r('H1','L2','F','static','judgement=target, momentary motivation=evaluator')
r('H2','L6','P','dynamic','B12c: date-indexed contexts; reversal is sequential')
r('H3','L6','P','dynamic','as H2')
r('H4','L2','P','dynamic','P4 localized overrating of drug region; tolerance dynamics')
r('H5','L7','Pt','outside-X','acts on evaluation mechanism (wireheading analogue)')
r('H6','L6','N','dynamic','evaluator resets; nothing misaligned at a snapshot')
r('H7','L2','F','static','forecast error = E')
r('H8','L5','N','category','')
r('H9','L5','N','category','')
r('H10','L1','N','outside-E','no pre-existing target')
r('H11','L1','N','outside-E','which elicitation is "true" undefined')
r('H12','L2','F','static','frame=context, F(c) invariant, F-hat(c) varies (normative invariance assumed)')
r('H13','L2','Pt','statistical','belief formation')
r('H14','L5','N','category','')
r('H15','L1','N','outside-E','which self is principal')
r('H16','L7','N','outside-X','choice changes F')
r('H17','L7','N','outside-X','F depends on reach')
r('H18','L2','F','static','proxy pursuit')
r('H19','L6','P','dynamic','habit = reference q (B12a); repetition moves q')
r('H20','L4','P','dynamic','state-varying capacity')
r('H21','L4','P','dynamic','beta->0 collapse to reference; learned')
r('H22','L6','P','strategic','intrapersonal game (B12c)')
r('H23','L1','N','outside-E','')
r('H24','L6','N','dynamic','evaluator depends on past behaviour')
r('H25','L2','P','strategic','designer finds tail of person\'s E (extremal, by a second optimizer)')
# --- I: institutions
r('I1','L2','P','strategic','agency loss = R_J; contracting is Stackelberg')
r('I2','L2','P','strategic','hidden action + contract')
r('I3','L5','N','strategic','types, equilibrium')
r('I4','L4','F','static','P20, Thm9')
r('I5','L4','F','static','Goodhart restated')
r('I6','L4','P','strategic','2/4 derived; causal, adversarial not')
r('I7','L2','F','static','B5')
r('I8','L6','Pt','dynamic','means->ends over time')
r('I9','L2','Pt','strategic','lobbying shapes evaluator')
r('I10','L2','F','static','procedure = proxy')
r('I11','L2','F','static','B5 / Goodhart')
r('I12','L2','F','static','metric replaces judgement')
r('I13','L2','F','static','X_anti / negative Cov_q (P14ii, Thm13b)')
r('I14','L1','N','strategic','B13 would move to F post-hoc')
r('I15','L1','N','strategic','B13 would move to F post-hoc')
r('I16','L1','N','outside-E','')
r('I17','L1','N','outside-E','')
r('I18','L1','N','strategic','manipulable aggregation')
r('I19','L2','Pt','strategic','contest')
r('I20','L5','Pt','strategic','second-best contracting')
r('I21','L2','P','dynamic','selection on cost with negative correlated response in quality (B11/Price)')
r('I22','L2','F','static','B5 across time')
r('I23','L1','N','strategic','')
r('I24','L5','N','strategic','')
r('I25','L6','P','dynamic','frozen evaluator, drifting contexts (P19)')
r('I26','L7','Pt','outside-X','agent redefines own mandate')
r('I27','L5','F','static','Hawthorne/Goodhart on auditability')
r('I28','L2','F','static','per-link evaluator error under capacity')
r('I29','L2','Pt','strategic','evaluator not additive in incentive; signalling')
r('I30','L1','N','outside-E','common agency')
# --- J: organism
r('J1','L2','F','static','tail extrapolation off q-support: P10(d)/P11')
r('J2','L5','F','static','ancestral vs modern contexts, P19')
r('J3','L2','F','static','instance of J1/J2')
r('J4','L2','F','static','PUSHBACK: causal Goodhart projects to E on the decoupling behaviours')
r('J5','L7','Pt','outside-X','as H5')
r('J6','L2','P','strategic','P4 localized host error; coevolution')
r('J7','L2','P','strategic','as J6')
r('J8','L2','P','strategic','as J6')
r('J9','L2','P','strategic','as J6')
r('J10','L1','N','strategic','')
r('J11','L1','Pt','strategic','parent as principal; begging game')
r('J12','L1','Pt','strategic','as J11')
r('J13','L2','Pt','strategic','exogenous rewrite of host evaluator by another agent')
r('J14','L2','F','static','PUSHBACK on §14: B11(iii) correlated response')
r('J15','L2','F','static','B11')
r('J16','L2','F','static','PUSHBACK on §14: population tilt anti-aligned with designated target (X_anti)')
r('J17','L2','F','static','proxy cue for relatedness')
r('J18','L5','P','strategic','cue-context shift, but reciprocity is a repeated game')
r('J19','L1','N','outside-E','target choice (fitness vs longevity)')
r('J20','L7','N','strategic','frequency-dependent coevolution')
# --- K: within genome
r('K1','L1','N','strategic','multilevel')
for i in ['K2','K3','K4','K5']: r(i,'L2','Pt','strategic','element transmission vs organism fitness; multilevel Price stated only')
for i in ['K6','K7','K8','K13','K15']: r(i,'L1','N','strategic','conflict between genomes/parties')
r('K9','L2','Pt','strategic','as J13')
r('K10','L2','P','dynamic','somatic selection vs organism target (B11)')
r('K11','L2','P','dynamic','as K10')
r('K12','L2','F','static','B10 / P4')
r('K14','L2','P','strategic','as J8')
# --- L: formal results
r('L1','L1','P','undetermined','as A10')
r('L2','L1','P','undetermined','as A11')
r('L3','L2','F','static','Cor13.1')
r('L4','L1','N','undetermined','as D2')
r('L5','L7','N','outside-X','causal influence diagrams')
r('L6','L7','N','outside-X','')
r('L7','L1','N','category','world models')
r('L8','L1','N','outside-E','')
r('L9','L1','N','strategic','')
r('L10','L4','P','strategic','as I6')
r('L11','L6','N','dynamic','')
r('L12','L5','F','static','P12/16')
r('L13','L5','F','static','P12(ii)/g3: q and F-hat trade off')
r('L14','L5','N','category','computability')
r('L15','L1','N','strategic','as D4')
# --- M: regularities
r('M1','L4','P','statistical','KL-slope derived (Gaussian); curvature and RM-size not')
r('M2','L4','P','statistical','error growth of a learned evaluator is statistical; P10(d) gives its consequence')
r('M3','L4','F','static','P4: p-hat(A) logistic in beta*M -> sharp for large M')
r('M4','L2','Pt','statistical','attribution to data')
r('M5','L5','P','category','as D7')
r('M6','L5','P','category','contexts; direction not predicted')
r('M7','L5','P','category','contexts; direction not predicted')
r('M8','L6','Pt','dynamic','training dynamics')
r('M9','L5','P','statistical','as B12')
r('M10','L3','Pt','statistical','as B11')
r('M11','L3','Pt','statistical','as B10')
r('M12','L5','F','static','as E12')
r('M13','L5','N','category','probes')
r('M14','L5','F','static','Goodhart on a deception detector (as F10)')
r('M15','L2','P','statistical','as D16')
r('M16','L3','N','category','coherence of goal pursuit')
assert len(R)==221, len(R)
